# Generated by Django 5.2.3 on 2025-06-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_version',
            field=models.IntegerField(default=0),
        ),
    ]
